# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 12:51
from __future__ import unicode_literals

import cases.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='figure',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=cases.models.case_directory_path),
        ),
    ]
