# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 15:26
from __future__ import unicode_literals

import cases.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20160525_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=cases.models.case_directory_path),
        ),
    ]
