# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 15:28
from __future__ import unicode_literals

import cases.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Add a flashy picture for the case listing page.', upload_to=cases.models.case_directory_path),
        ),
    ]
